### ISSUE TITLE
ArrayIndexOutOfBounds Error When Training New Corpus

### ISSUE THREAD

**Issue by Calvinnncy97** [datquocnguyen/LFTM#13]
I face the following error when I am trying to train a new pre-processed corpus:
`java.lang.ArrayIndexOutOfBoundsException                                                                                        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)                                                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)                                            at java.lang.reflect.Constructor.newInstance(Unknown Source)                                                            at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)                                              at java.util.concurrent.ForkJoinTask.reportException(Unknown Source)                                                    at java.util.concurrent.ForkJoinTask.join(Unknown Source)                                                               at java.util.concurrent.ForkJoinPool.invoke(Unknown Source)                                                             at utility.Parallel.loop(Unknown Source)                                                                                at utility.Parallel.loop(Unknown Source)                                                                                at models.LFLDA.optimizeTopicVectors(Unknown Source)                                                                    at models.LFLDA.inference(Unknown Source)                                                                               at LFTM.main(Unknown Source)                                                                                    Caused by: java.lang.ArrayIndexOutOfBoundsException: 0                                                                          at models.TopicVectorOptimizer.<init>(Unknown Source)                                                                   at models.LFLDA$1.compute(Unknown Source)                                                                               at utility.Parallel$LoopIntAction.compute(Unknown Source)                                                               at utility.Parallel$LoopIntAction.compute(Unknown Source)                                                               at utility.Parallel$LoopIntAction.compute(Unknown Source)                                                               at java.util.concurrent.RecursiveAction.exec(Unknown Source)                                                            at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)                                                             at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)                                                  at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)                                                          at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) `

The dataset I used is attached in this post. Can someone help me with this? I read the previous issue and made sure there is no empty lines in my code. 

Please help. 

Thank you so much guys. 

Best regards,
Kelvin
[LFDLA-Challenges-Full.txt](https://github.com/datquocnguyen/LFTM/files/7647712/LFDLA-Challenges-Full.txt)

**Comment by Calvinnncy97** [comment]
For future readers who face the same problem, this issue can be solved by making sure Java SDK is installed properly and added to PATH in Environment Variable (for Windows device). Then, restart PowerShell before trying again.
