### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by kevinbsc** [datquocnguyen/LFTM#4]
The size of corpus is about 250M. I am getting an error message. Any ideas?

Reading topic modeling corpus: test/corpus.txt
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at models.LFLDA.<init>(Unknown Source)
        at LFTM.main(Unknown Source)

**Comment by datquocnguyen** [comment]
You should increase Java heap size.
